### ISSUE TITLE
MC_PRE/POST_ADD/REMOVE_COSTUME

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#132]
Two callbacks, each for adding/removing a costume. Would have the costume's CostumeDesc and the player it's being added to as arguments. Returning true on the PRE callbacks would prevent the costume from being added/removed respectively.

This is just about the last thing I'd love to see for my costume dreams to be fulfilled

**Comment by MrHeadcrab2** [comment]
bumping this, a clean way to do custom costume anm2s would be so nice

**Comment by epfly6** [comment]
Added 199c5395
