### ISSUE TITLE
Game doesn't start properly while Repentogon is installed (possible dsound.dll problem?)

### ISSUE THREAD

**Issue by ItzDFPlayer** [TeamREPENTOGON/REPENTOGON#156]
For some reason game just doesn't start with Repentogon, it just stucks on initial black screen, no log is created either, tried removing all mods, redownloaded all game files in Steam by removing all files/folders in game directory and verifying files, reinstalling the game did nothing too (installing Repentogon through .exe did nothing to the game (even tho files were downloaded), manual install causes this black screen issue)

After some digging around, I've found out that the game launches if dsound.dll is removed (but Repentogon expectedly doesn't work then)

**Comment by jsgnextortex** [comment]
Did you try making an exception in your antivirus or disabling it before installing and launching repentogon? Because it sounds like the dll may be getting blocked.

**Comment by ItzDFPlayer** [comment]
Tried addding game folder into exclude list and disabling Windows Defender, nothing

**Comment by ItzDFPlayer** [comment]
And nothing in Windows Defender history about dsound.dll, recent one is only Repentogon installer .exe

**Comment by jsgnextortex** [comment]
Did you try disabling Windows defender, copying the dll, launching the game and seeing if that works?. Also, are you sure you dont have any other kind of antivirus software that could be interfering?

**Comment by ItzDFPlayer** [comment]
Nope, only Windows Defender, just tried disabling protection, redownloading latest release from github, copying files and launching the game, still black screen

**Comment by Sylmir** [comment]
Are there dsound.log / libzhl.log / repentogon.log files generated next to the game's executable ? If so, what's their content ?

**Comment by ItzDFPlayer** [comment]
sadly it's not generated, also if I removed game folder in Documents/My Games/ it creates empty without anything

**Comment by ItzDFPlayer** [comment]
maybe some Windows 11 Dev issue? tried launching isaac-ng.exe with W7/8 compatibility, doesn't help

**Comment by jsgnextortex** [comment]
I still think theres something in your machine blocking the dll but I cannot think of what that may be, if you figure anything out or get any more clues on the issue please let us know. We will update this issue if we are ever able to replicate this one.

**Comment by ItzDFPlayer** [comment]
I've reinstalled Windows 11 to Stable build and now it works fine, thanks
