### ISSUE TITLE
Look into letting ImGui accept multiline text natively

### ISSUE THREAD

**Issue by jerbmega** [TeamREPENTOGON/REPENTOGON#157]

**Comment by oilyspoily** [comment]
Bumping this!
Doing fortunes in Fiend Folio is impossible right now at the moment.
I'm dying.

**Comment by jerbmega** [comment]
Done in 6e8006d. Horizontal scrolling isn't supported yet as ImGui doesn't natively support this. There's an open issue with a workaround in [orconut/imgui#383](https://github.com/ocornut/imgui/issues/383), with performance caveats. I'd consider our buffer to be "small" so it may be okay, but we'll need to fork ImGui for this for submodule purposes (or otherwise figure out how to get CMake to apply patches at build time without affecting Git history)

**Comment by jerbmega** [comment]
Horizontal scrolling fully implemented. It's hacky but functional.
