### ISSUE TITLE
Locked characters appears on the local co-op character select

### ISSUE THREAD

**Issue by AndreDoruk** [TeamREPENTOGON/REPENTOGON#159]
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/81973147/87f8a9e2-a8b2-4057-b67d-1cc3ce799900)
locked on main menu

![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/81973147/0421500c-ab2f-48e3-a119-d55c3aae3892)
(no image as not implemented)
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/81973147/76fb21c3-2831-4fad-8ef6-0bd269921715)
you can freely select it even tho they are locked on the main menu

**Comment by ConnorForan** [comment]
Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/85b4bed0eec3f297296a99d1a4415ff23f8b47e3
