### ISSUE TITLE
Crawlspaces lose their floor sprites

### ISSUE THREAD

**Issue by Cuerzor** [TeamREPENTOGON/REPENTOGON#169]
![QQ图片20240102131304](https://github.com/TeamREPENTOGON/REPENTOGON/assets/22266114/2dce52ca-ac6e-4869-ae64-df0e26ea43dc)

**Comment by epfly6** [comment]
Reopening this issue, since fix is not published to public build yet

**Comment by steviegt6** [comment]
Oh yeah, I've been meaning to report this but never got to confirming it was REPENTOGON-only. lol

**Comment by namishere** [comment]
Currently fixed in development build, will be fixed in next public release
