### ISSUE TITLE
Getter functions for status effect countdowns and other related values

### ISSUE THREAD

**Issue by TaigaTreant** [TeamREPENTOGON/REPENTOGON#181]
Realized while trying to get status effects to synchronize between enemy segments that Entity:CopyStatusEffects() would completely override any and all status effect related values on the target entities. This means that currently there isn't a good way of handling the case of different segments having different status effects active, as one entity will wind up overwriting the other's statuses.

As such, it would be good to have getter functions for the status effect countdowns (freezeCountdown, poisonCountdown, slowingCountdown, etc.) as well as other known related status effect variables needed for the Entity:AddStatus() functions (poisonDamage, knockbackDirection, etc.). This would allow for the manual handling of status effect copying by said AddStatus functions.

**Comment by epfly6** [comment]
Added in v1.0.5!
