### ISSUE TITLE
Lua method to check if you're in-game

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#184]
MC_EXECUTE_CMD now works from the menu. Is there a good way to check that we're in a run? Otherwise, commands can easily crash the game. I see there's an Isaac::IsInGame, but it doesn't seem to be exposed in the Lua API. As a workaround, we can check the number of players, but something more straight forward would be nice.

**Comment by namishere** [comment]
Will be available as Isaac.IsInGame next update
