### ISSUE TITLE
ImGui Formatting params broken

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#186]
ImGui has a few methods that take Formatting params (AddDragInteger/AddDragFloat/etc). If you use the params exactly as shown in the docs, the formatting breaks (e.g. "%d%" or "%.3f"). If you leave the params off then it works fine. I'm not sure if this is a doc bug or a code bug.

**Comment by wofsauge** [comment]
this was fixed now with commit 0bb0e42
Also added an example usage in the imgui testing .lua file
