### ISSUE TITLE
HUD and Camera bug

### ISSUE THREAD

**Issue by Joracy** [TeamREPENTOGON/REPENTOGON#188]
Don't know exactly why but after game crash an additional HUD has appeared and camera start smooth follow character. Complete reinstallation game and mods doesn't help at all. Disabling with -repentogonoff fixes the problems.
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/155489313/91abad91-287a-485b-b63d-f0c18f21d1df)

**Comment by im-tem** [comment]
looks like a community remix problem......

**Comment by jerbmega** [comment]
Yes, this is a Community Remix issue. A recent update to that accidentally enabled many of its settings- these are all implemented by CR, not us.
