### ISSUE TITLE
Modded characters should be able to donate the Greed Donation Machine

### ISSUE THREAD

**Issue by oilyspoily** [TeamREPENTOGON/REPENTOGON#189]
![2024-01-02 20-28-51](https://github.com/TeamREPENTOGON/REPENTOGON/assets/50062278/16f423b5-a703-498a-8fa9-849a3bd3a4b0)
Modded characters are always stuck at 100% jam rate when finishing Greed mode.

Why is it like this... Fix it! Or else I'll get angry.

Kidding though, I do wonder if this is possible to fix?
Probably possible but really hard, definitely still very annoying though and should be looked at in the future!

**Comment by namishere** [comment]
Custom characters are hardcoded to have a 99.9% jam rate. We can definitely change this, will just take one part asm patching to one part savedata handling.

**Comment by wofsauge** [comment]
Feature is added now with b225bb4
