### ISSUE TITLE
ItemPool:HasTrinket() seems to always return true

### ISSUE THREAD

**Issue by Spearkiller** [TeamREPENTOGON/REPENTOGON#190]
Wanted to make an item drop a trinket upon the very first time seeing it (similar to Match Book), but using HasTrinket() to check always returns true (Tested by spawning it with Isaac.Spawn and through the console), and ItemPool:RemoveTrinket() seems to have no effect.

Furthermore, ItemPool:GetNumAvailableTrinkets() returns a boolean when called; I had a print statement printing when picking up my item and it always printed "true" when calling this.

**Comment by epfly6** [comment]
I was not able to replicate your issue with HasTrinket check, can you please provide your code?
![Image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/cdc89e22-f1ab-49cb-a7fe-52b7751abff6)

**Comment by epfly6** [comment]
ItemPool:GetNumAvailableTrinkets() issue will be fixed, I should have looked at my shameful copypasting carefully ._.

**Comment by epfly6** [comment]
> I was not able to replicate your issue with HasTrinket check, can you please provide your code? ![Image](https://private-user-images.githubusercontent.com/36567300/293875513-cdc89e22-f1ab-49cb-a7fe-52b7751abff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzQzNjEsIm5iZiI6MTcwNDI3NDA2MSwicGF0aCI6Ii8zNjU2NzMwMC8yOTM4NzU1MTMtY2RjODllMjItZjFhYi00OWNiLWE3ZmUtNTJiNzc1MWFiZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA5Mjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyODU4NzE0MjNhNDc3ZDg1OTExYzc2MWY2YzQ1Y2NhMDYzNTRlMWI3ZmMxYjNjZWQ2YWZiYWVlMTZmMGJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KN0OJwdHxHGhFXOUjHOjSFf6JFltWde2_tBgsNff4j0)

But from what I see in decompilation for match book, the game first checks boolean from ItemPool::RemoveTrinket(matchStickID), and if it's true, then it spawns Match Stick trinket

**Comment by Spearkiller** [comment]
```print(ICM.Itempool:HasTrinket(TrinketType.TRINKET_POKER_CHIP)) -- Prints true
    print(ICM.Itempool:RemoveTrinket(TrinketType.TRINKET_POKER_CHIP)) -- Prints false
    print(ICM.Itempool:HasTrinket(TrinketType.TRINKET_POKER_CHIP)) --Prints true
    ICM.Functions.SpawnNearPosition(EntityType.ENTITY_PICKUP,PickupVariant.PICKUP_TRINKET,TrinketType.TRINKET_POKER_CHIP,player.Position,Vector.Zero,player)
    print(ICM.Itempool:HasTrinket(TrinketType.TRINKET_POKER_CHIP)) --Prints true```
    
    This occurs when using either the cached ICM game and itempool variables, or if reusing Game() and ItemPool().

**Comment by epfly6** [comment]
Weird, works for me
![изображение](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/b454ef55-c94d-4108-85ad-3384069373df)

**Comment by epfly6** [comment]
Tried to call from PRE_ADD_COLLECTIBLE, but I'm still getting positive results :/

**Comment by Spearkiller** [comment]
I can confirm that this was an issue on my end; Something to do with the mod loading process was somehow screwing with this, and I have fixed it. Apologies for the trouble (But hey, at least a bug was found in the process, so that's worth something)

**Comment by epfly6** [comment]
I will close this issue completed, since ItemPool:GetNumAvailableTrinkets was bugged before, but fixed later
