### ISSUE TITLE
The Fiend Folio enemy "Unshornz" doesn't seem to work.

### ISSUE THREAD

**Issue by BoardAnims** [TeamREPENTOGON/REPENTOGON#193]
I'm not sure if it's Repentogon that's causing this issue, but whenever i encounter a Unshornz enemy it simply stays still and doesn't hug the walls like it's supposed to. It doesn't slide around or anything, it just stays still until it gets killed.

The console gives this error:
`[INFO] - Lua Debug: Error in "MC_NPC_UPDATE" call from "Fiend Folio": ...ed_2851063440/ffscripts/guwah/utilities/wallmovement.lua:210: WallHuggerInit needed to use WallHuggerMovement
Stack Traceback:
  in method error
  ...ed_2851063440/ffscripts/guwah/utilities/wallmovement.lua:210: in function 'WallHuggerMovement'
  ...heated_2851063440/ffscripts/ferrium/enemies/unshornz.lua:100: in function 'Update'
  ...iendfolio-reheated_2851063440/ffscripts/ferrium/main.lua:2370: in function at line 2368`

**Comment by jerbmega** [comment]
This is a Fiend Folio issue. Our Vector reimplemention does more sanity checking than the base game's implementation and catches more (valid!) errors as a result. This is in an effort to reduce the amount of arbitrary crashed that can happen with mods. We have similar mechanisms in place for some RNG functions that the game accepted any value for before but really shouldn't have.

In this particular case, we're catching a divide by zero (should be above the error you sent us) that needs to be fixed on Fiend Folio's end.
