### ISSUE TITLE
EntityPlayer:GetTransformationPartCount and EntityPlayer:AddTransformationPart

### ISSUE THREAD

**Issue by BreavyTF2** [TeamREPENTOGON/REPENTOGON#211]
There is currently no way to directly see the transformation part count of a player. Allows transformation parts to be done without using xml tags allows non collectibles to contribute to them.

**Comment by epfly6** [comment]
[Player:GetPlayerFormCounter](https://repentogon.com/EntityPlayer.html?h=player#getplayerformcounter)
[PlayerIncrementPlayerFormCounter](https://repentogon.com/EntityPlayer.html?h=player#incrementplayerformcounter)
