### ISSUE TITLE
ImGui has problems displaying French

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#212]
lua Isaac.DebugString(Isaac.GetLocalizedString('Entities', '#MOMS_HEART', 3))

logs: Le Cœur de Maman

lua print(Isaac.GetLocalizedString('Entities', '#MOMS_HEART', 3))

prints: Le C?ur de Maman

**Comment by frto027** [comment]
fixed in this [commit](https://github.com/TeamREPENTOGON/REPENTOGON/commit/a8e3feb3b3c48b357d1aaabb8db7165b920d3ee9)
