### ISSUE TITLE
GetLocalizedString doesn't accept Options.Language

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#213]
You can't do this:

Isaac.GetLocalizedString('Entities', '#MOMS_HEART', Options.Language)

which is equivalent to:

Isaac.GetLocalizedString('Entities', '#MOMS_HEART', 'fr')

Instead it needs to be:

Isaac.GetLocalizedString('Entities', '#MOMS_HEART', 3)

I know you can use GetString in this case. It just seems weird you can't pass around the language field the api sets.

**Comment by epfly6** [comment]
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/2ff69a71-78ec-4cef-83e7-af52157e90cb)
