### ISSUE TITLE
Interacting with an ImGui ControllerInput with no controller breaks ImGui

### ISSUE THREAD

**Issue by Syntax-Sculptor** [TeamREPENTOGON/REPENTOGON#214]
When interacting with an ImGui ControllerInput without a controller, you are permanently stuck in the state where it is expecting you to input a controller key, with pressing escape not canceling the prompt. This effectively prevents you from interacting with any other ImGui elements.

**Comment by wofsauge** [comment]
This issue should be fixed now with commit 65c796b
