### ISSUE TITLE
i am a gog user i never had a problem with other mods but REPENTOGON doesn't work from me 

### ISSUE THREAD

**Issue by NotVoid404** [TeamREPENTOGON/REPENTOGON#220]
just as the title says.
first of all i turned off real-time protection, and just dumped REPENTOGON in the files and it said: 
unable to load REPENTOGON resources. please make sure that all the files copied correctly and that the mods are enabled in the mods menu.
plus when i enable the mods menu even when there is no mods the game crashes.
by the way with other mods it just freezes then it back to normal.
and yes, you can mod tboi manually so please help me.

**Comment by namishere** [comment]
REPENTOGON is unsupported on all versions besides the Steam release of v1.7.9b.J835. Releases on other platforms, such as Epic Games Store and Good Ol' Games, have not been updated in a year plus are are out of date. Please contact your local Nicalis for more information.

**Comment by im-tem** [comment]
as an actual gog user, can you please report the full version number of your game? i'd want to have a confirmation on an assumption we have
