### ISSUE TITLE
Move function for ASMPatch

### ISSUE THREAD

**Issue by namishere** [TeamREPENTOGON/REPENTOGON#222]
I am writing a generic patch to be used multiple times with various different registers that requires me to `mov [destReg], [srcReg]`. The current `Move[x]` functions that have a register as the destination are in the form of `mov dword ptr ds:[destReg], srcReg`, which does not work for this patch and crashes. I would like a `ASMPatch.Move(ASMPatch::Registers srcReg, ASMPatch::Registers destReg)` that equates to `mov [destReg], [srcReg]`. Thank you!

**Comment by Sylmir** [comment]
I didn't realize this what was you wanted to do at first. On x86 memory-to-memory moves are not possible. If you want to do `*eax = *ebx`, you need to do `ecx = *ebx; *eax = ecx;`.

**Comment by Sylmir** [comment]
Update: register-to-register copy is requested, not memory-to-memory

**Comment by namishere** [comment]
`CopyToRegister` does what this issue is requesting. Marking resolved.
