### ISSUE TITLE
Game is unable to start, window frozen and does not respond; Runtime C++ Error after a long, agonizing wait

### ISSUE THREAD

**Issue by cannon9009** [TeamREPENTOGON/REPENTOGON#224]
When using REPENTOGON, my game freezes on a black screen while loading at the start and does not respond. Eventually after a long enough wait, a Runtime Error causes the game to close.

Here are some log files. I do not know if they will be useful. Look through them if you want.

[repentogon.log](https://github.com/TeamREPENTOGON/REPENTOGON/files/13846814/repentogon.log)
[zhl.log](https://github.com/TeamREPENTOGON/REPENTOGON/files/13846816/zhl.log)
[isaacv1.7.9b.J835-20240105-160332-30960-14888.txt](https://github.com/TeamREPENTOGON/REPENTOGON/files/13846818/isaacv1.7.9b.J835-20240105-160332-30960-14888.txt)
[log.txt](https://github.com/TeamREPENTOGON/REPENTOGON/files/13846819/log.txt)

I am running on Windows 11's Insider previews, specifically the Canary builds.

**Comment by namishere** [comment]
You are somehow running out of memory while trying to load mods. Remains to be seen if this is related to the exception caught in repentogon.log

**Comment by cannon9009** [comment]
> You are somehow running out of memory while trying to load mods.

Is there a way to fix this?

**Comment by namishere** [comment]
I'm closing this for now out of inactivity. Please let me know if this is still an issue.
