### ISSUE TITLE
player:AddBoneOrbital() freezes the game on use

### ISSUE THREAD

**Issue by Spearkiller** [TeamREPENTOGON/REPENTOGON#227]
`  function ICM.Trinkets.ThirteenthRib.TestBoneOrbitals(_, killed)
    for _, player in pairs(PlayerManager:GetPlayers()) do 
      player:AddBoneOrbital(killed.Position)
    end
  end
  IpecacMod:AddCallback(ModCallbacks.MC_POST_NPC_DEATH, ICM.Trinkets.ThirteenthRib.TestBoneOrbitals)`

Tested using the following callback to get it to execute after every enemy death.
player:AddBlueSpider(killed.Position) works fine here.

No Lua stack trace is available, the log is just filled with a series of '[INFO] - Lua stack trace:'

**Comment by namishere** [comment]
Fixed by 4d8a83e3, will be available next release
