### ISSUE TITLE
Active collectible's vardata not changes in callbacks

### ISSUE THREAD

**Issue by BrakeDude** [TeamREPENTOGON/REPENTOGON#229]
Using MC_PRE_USE_ITEM and MC_USE_ITEM callbacks "customvardata" always returns 0 even if it was changed.

**Comment by epfly6** [comment]
Works for me, provide your code please
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/c49249f2-08c9-43da-9207-ef580dd5405d)

**Comment by BrakeDude** [comment]
```lua
mod:AddCallback(ModCallbacks.MC_USE_ITEM, function(_, collectible, rng, player, flags, slot, data)
    if data > 0 then 
        return {
            Discharge = false,
            Remove = false,
            ShowAnim = false,
        }
    end
end)
   ```

**Comment by epfly6** [comment]
As stated in documentation for vanilla API "USE_CUSTOMVARDATA - If set, forces UseActiveItem to use the CustomVarData argument instead of the active item's stored VarData", so I assume you expecting those callbacks return from what stored in VarData, instead of CustomVarData

**Comment by BrakeDude** [comment]
So, SetActiveVarData modifies "customvardata" and Jar of Wisps also uses customvardata then?

**Comment by epfly6** [comment]
SetActiveVarData modifies VarData
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/b932a6f7-b1e8-427f-8615-4dc108f0f4d7)
