### ISSUE TITLE
FindInRadius can't detect effects

### ISSUE THREAD

**Issue by nazardz** [TeamREPENTOGON/REPENTOGON#232]
can't detect poison clouds
`local effects = Isaac.FindInRadius(player.Position, removeRadius, EntityPartition.EFFECT)
for _, effect in pairs(effects) do
  if effect.Variant == EffectVariant.SMOKE_CLOUD then
	  effect:Remove()
  end
end`

**Comment by jerbmega** [comment]
Does this work without Repentogon?

**Comment by epfly6** [comment]
FindInRadius works with EntityPartition.EFFECT, if effect entity has set EntityCollisionClass other than ENTCOLL_NONE
https://github.com/wofsauge/IsaacDocs/pull/467
