### ISSUE TITLE
Windows Security Warning

### ISSUE THREAD

**Issue by gnaomo** [TeamREPENTOGON/REPENTOGON#235]
After starting TBOI from steam and clicking yes to update

![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/38522864/1ff49cab-0bdc-47f4-b550-65e3a6642703)

**Comment by im-tem** [comment]
not much we can do, feel free to check out our source code if you want to ensure its all good

**Comment by jerbmega** [comment]
Of note: the `!ml` tag at the end means this is a machine learning detection- in other words, an (incorrect) educated guess.
