### ISSUE TITLE
Bone plus Eternal heart Initialization Hud render error

### ISSUE THREAD

**Issue by eggviper3** [TeamREPENTOGON/REPENTOGON#238]
I'm trying to make a character who starts with one empty bone heart and one eternal heart. Upon starting, the health appears to be only a half soul heart and an eternal heart. Upon taking damage and losing the eternal heart, it transforms into a bone heart, so it appears to be only rendering incorrectly visually in the HUD.

Testing further, this extends to only having the one bone heart at the start and no eternal. Can confirm it still seems to only be the HUD rendering incorrectly, as spawning a red heart in allows the red heart to be taken, transforming the heart into a bone heart visually.

**Comment by eggviper3** [comment]
happens with two bone hearts as well

**Comment by jsgnextortex** [comment]
fixed on b4d2909
