### ISSUE TITLE
the updater is being reported by windows defender as Trojan:Win32/Malgent!MSR

### ISSUE THREAD

**Issue by agalq13** [TeamREPENTOGON/REPENTOGON#241]
![Снимок экрана 2024-01-08 230747](https://github.com/TeamREPENTOGON/REPENTOGON/assets/71724834/e7b8c202-bf17-410f-b730-52e14959f116)

**Comment by jerbmega** [comment]
False positive.

* The updater is packaged with PyInstaller with the --onefile option. Bad actors do the same thing, and the only thing Defender sees as the same is the PyInstaller bootloader, so it assumes the file is malicious. Not much we can do.

* Of note, the `!ml` tag at the end stands for **machine learning**, indicating Defender is making a guess here.

Releases are solely done via GitHub actions for both REPENTOGON and the installer. In theory, an identical build process will generate an identical hash, so you can be sure that the releases we're building aren't being tampered with.

**Comment by jerbmega** [comment]
There was one version of the installer that got flagged as Malgent/MSR like you're seeing, though. Still a false positive but be sure you've got the latest installer either way.
