### ISSUE TITLE
ItemPool:GetRemovedCollectibles item ids are offset by one

### ISSUE THREAD

**Issue by thicco-catto** [TeamREPENTOGON/REPENTOGON#246]
The table that ItemPool:GetRemovedCollectibles has all item ids offset by one, so if brimstone (118) is removed, index 119 will be set to true instead.
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/67873211/8712c9d1-5008-4628-aa1b-1bc78ca20cd0)

**Comment by thicco-catto** [comment]
Also happens with ItemPool:GetRoomBlacklistCollectibles
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/67873211/6e2a3526-b05c-453e-bc8f-5bb7b92e7b62)

**Comment by epfly6** [comment]
Fix will available publicly in v1.0.5
