### ISSUE TITLE
XMLData Achievement sourceid gets overwritten

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#251]
XMLData.GetEntryById(XMLNode.ACHIEVEMENT, 637)

By default, returns:

gfx=Achievement_DeadGod.png
steam_icon=Achievement_DeadGod.png
text=
gfxroot=gfx/ui/achievement/
steam_description=
steam_name=Dead God
sourceid=BaseGame
id=637
name=Dead God

If you enable a mod that has a content/challenges.xml it returns:

gfxroot=gfx/ui/achievement/
gfx=Achievement_DeadGod.png
steam_name=Dead God
text=
steam_description=
steam_icon=Achievement_DeadGod.png
sourceid=2966818059
relativeid=637
id=637
name=Dead God

"BaseGame" gets overwritten with the mod ID making it harder to figure out if it came from the base game or a specific mod.

**Comment by jsgnextortex** [comment]
I could swear I fixed this one...just comes back to haunt me in Deja Vu form, Fixed in 1.0.5 (again!)
