### ISSUE TITLE
Custom achievement ID not ignored

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#252]
I was testing with the Community Remix mod and added an ID to the first achievement (content/achievements.xml):

    <achievement name="Adam" text='' gfx="achievement_cr_adam.png" id="1" />

lua print(Isaac.GetAchievementIdByName('Adam')) : 1

lua for k,v in pairs(XMLData.GetEntryById(26, 638)) do print(k, v) end

returns:

conditionvalue=
text=
gfx=achievement_cr_adam.png
id=1
name=Adam
sourceid=3128085237
condition=table: 80B50680
gfxroot=gfx/ui/achievement/
relativeid=1

Different parts of the API seem to think it's 638 or 1.

You can use 1 or 638 with the achievement/lockachievement commands.

1 is normally the Magdalene achievement.

The docs say this should be ignored.

**Comment by jsgnextortex** [comment]
Nice catch!, while setting up arbitrary ids is not adviced for modded stuff overall (unless its needed, like for items/costumes on some cases), this still shouldnt happen and its....well, pretty bad.
Fixed in 1.0.5!
