### ISSUE TITLE
Game crashes when I start run

### ISSUE THREAD

**Issue by Techmox** [TeamREPENTOGON/REPENTOGON#253]
Hello. I have an issue with REPENTOGON. After installation, my game crashes and turns off whenever I start a new run (with any character, oryginal and modded ones). I can't play.

**Comment by epfly6** [comment]
Ipecac Community Mod enabled?

**Comment by Techmox** [comment]
> Ipecac Community Mod enabled?

yeah! I'll try to disable it and then we'll see
