### ISSUE TITLE
XMLData inconsistencies

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#255]
These are all probably edge cases, but I've been poking around...

1) BaseGame confusion.

XMLData Achievement.sourceid comes from metadata.xml id if set or a lowercase version of the mod folder name.

If the folder name is BaseGame, that gets converted to sourceid=basegame

However, if you set the id to BaseGame then the Achievement.sourceid becomes BaseGame and looks like it came from the base game.

This doesn't seem to be consistent across all types. Player.sourceid, for example, seems to validate the id field and if it's not a number falls back to the lowercase folder name.

2) Non-number id confusion

For example, if a mod doesn't have an ID set then the MOD data can be:

mod.name = test
mod.id = test (inherits the name)

You can't then use GetEntryById on this object because you can't pass a string as the id.

This also gets confusing if you try to match Achievement.sourceid (which doesn't inherit mod.name but rather the folder name) with mod.id

**Comment by jsgnextortex** [comment]
Mods will only have a name as an id if they had their metadata.xml deleted or if its a mod you are developing locally, ids as names are an edge case in itself, I dont even want to get over the case of a mod calling itself "Base Game" but if one does well....fuck them, they are asking for trouble for the sake of it, no mod is going to be called that, lol.
