### ISSUE TITLE
Modded Tainted completion marks

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#256]
This is a super edge case... just wanted to report/document...

It's possible to create modded characters like this in players.xml:

regular: test-Tainted-
tainted: test

They both end up using the same entry in completionmarksX.json: xxx-test-Tainted-

**Comment by jsgnextortex** [comment]
If you specifically try to fuck things up, you will fuck things up. No you should not name your character charactername-Tainted-
