### ISSUE TITLE
Entity:CopyStatusEffects shouldn't remove status effects from the target entity

### ISSUE THREAD

**Issue by PixelPlz** [TeamREPENTOGON/REPENTOGON#264]
Currently it immediately removes any status effects from the target that the copying entity doesn't have.

**Comment by namishere** [comment]
While not explicitly intended behavior, I feel like it's proper. Will work on an option to only apply new status effects; will take me a little to figure out the best way to handle ColorParams doing this

**Comment by PixelPlz** [comment]
It makes it useless for enemies / bosses that use multiple entities, which would be the main use case for it. So at least an option to prevent this would be appreciated
