### ISSUE TITLE
Returning a table with DamageFlags argument in MC_ENTITY_TAKE_DMG callback takes no effect

### ISSUE THREAD

**Issue by BadPig03** [TeamREPENTOGON/REPENTOGON#279]
For the callback MC_ENTITY_TAKE_DMG, I tried to return a table with DamageFlags argument like this `return { DamageFlags = flags | DamageFlag.DAMAGE_NO_PENALTIES }`. But in reality, penalties were still applied(such as devil deal chance dropping). 
I also tried `player:TakeDamage(amount, flags | DamageFlag.DAMAGE_NO_PENALTIES, source, countdown) return false`, which was perfectly worked.

**Comment by ConnorForan** [comment]
Core issue identified as being that the modified DamageFlags don't appear to take effect for the PLAYER specifically, despite the modified flags appearing in MC_POST_ENTITY_TAKE_DMG. Modifying the flag works as expected for any other entity type.

Will investigate further & try to fix

**Comment by ConnorForan** [comment]
Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/dffb78e57ede5d53f508e24892a5c9f40737013a
