### ISSUE TITLE
:GetMultiShotPositionVelocity - doesn't accept ShotDirection

### ISSUE THREAD

**Issue by nazardz** [TeamREPENTOGON/REPENTOGON#280]
So I'm sure it's vector and I even tried to use Vector.One and Vector(vel.X, vel.Y)

--- error
"MC_POST_PEFFECT_UPDATE" from "Eclipsed" failed: ...ebirth/mods/eco/scripts_eclipsed/echars/player_abihu.lua:349: bad argument #3 to 'GetMultiShotPositionVelocity' (Vector expected, got userdata)
Stack Traceback:
  in method GetMultiShotPositionVelocity

--- code
print(vel, vel.X, vel.Y)
local posvel = player:GetMultiShotPositionVelocity(idx, WeaponType.WEAPON_TEARS, vel, 14, player:GetMultiShotParams(WeaponType.WEAPON_TEARS))

**Comment by nazardz** [comment]
I'm on v 1.0.4

**Comment by epfly6** [comment]
> I'm on v 1.0.4
Update to v1.0.5
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/da56f60f-fa8c-453c-b644-5d0468a17056)
