### ISSUE TITLE
Mother chase for knife piece 2 music playing indefinitely

### ISSUE THREAD

**Issue by Intancote** [TeamREPENTOGON/REPENTOGON#281]
After you take the knife piece in caves/ashpit and start the chase, the music for the chase also plays. After you exit the chase sequence the music is supposed to stop. But it will continue to play and no other music (that I know of except for main menu) will play. The music will stop and then play again from the beginning every time time you go to a new room/floor. Exiting and reentering the run doesn't fix it and neither will starting a new run. But a restart of the game will fix the bug.

I tested this without repentogon and it functions as it should.

**Comment by epfly6** [comment]
Can't confirm

https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/a3ab34e0-083c-42cd-a1ec-c9d77a4c8db0
