### ISSUE TITLE
"Multiple funcions/variable were not found" error when opening game

### ISSUE THREAD

**Issue by Gabzr** [TeamREPENTOGON/REPENTOGON#282]
Title. Removing repentogon fixes it. Anyone knows hot to make it work? 
Tried to search the error on google/github, couldn't find anything useful.

Game version: v1.7.9b
Method of Installation: From site, droping the .Exe in game installation folder and executing.

Edit1: Tried to copy the files from the github to game inst folder, game starts but not with repentagon.

![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/96807972/0673c4bd-7525-4d02-b34c-6f835d25c27f)

**Comment by jerbmega** [comment]
You do not have the correct version, you specifically need v1.7.9b.**J835**.

If you bought the game on Steam, validate your game files and ensure you are not in the online alpha, otherwise you're on your own.
