### ISSUE TITLE
EntityPlayer:DropCollectible returns nil when ExistingPedestal is nil

### ISSUE THREAD

**Issue by dpower12** [TeamREPENTOGON/REPENTOGON#285]
`EntityPlayer:DropCollectible(Collectible, ExistingPedestal, RemoveFromPlayerForm)`
the function returns the existing pedestal when used, but the issue is when `ExistingPedestal` isn't provided, as the return is also nil, while the function spawns a pedestal
it can be played around with creating a timer and checking one frame after for a pedestal with the same subtype, but it would be a lot better if the function returned directly the newly spawned pedestal when used

**Comment by namishere** [comment]
oversight, will fix

**Comment by namishere** [comment]
I am deeply sorry for letting this slip past my mind. I've fixed this for our next release.
