### ISSUE TITLE
Ability to change EntityPickup:GetCoinValue()

### ISSUE THREAD

**Issue by dpower12** [TeamREPENTOGON/REPENTOGON#290]
the function works fine for vanilla coins, but modded coins it always returns 1 (As long they are PickupVariant.PICKUP_COIN)
being able to assing the right value would make it easier to count the value of coins without having to make value tables
making mod compatibility easier by using this method

**Comment by namishere** [comment]
Use `MC_PICKUP_GET_COIN_VALUE` or xml attribute `coinvalue` (will close this after documenting the xml)
