### ISSUE TITLE
ItemOverlay is missing GetDelay and GetPlayer functions present in docs

### ISSUE THREAD

**Issue by Gemboat** [TeamREPENTOGON/REPENTOGON#297]
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/88180001/a4d3a30a-b34a-40f1-926f-58d5572c021d)
Either the docs are wrong, or these two functions weren't made visible to lua.

**Comment by wofsauge** [comment]
These function got re-added now. Thanks for the report.
