### ISSUE TITLE
MC_PRE/POST_PAUSE_SCREEN_RENDER PauseStats arg returns a useless Sprite object

### ISSUE THREAD

**Issue by Gemboat** [TeamREPENTOGON/REPENTOGON#299]
The first arg, PauseBody, returns as expected. But PauseStats gives a Sprite object that doesn't do much and behaves strangely with a few things (PauseStats:Reset() or :LoadGraphics() crashes the game, :GetFilename() returns an empty string, etc.).

**Comment by jsgnextortex** [comment]
Yea, nice catch, thankfully I noticed this today when I implemented the PauseMenu goodied, so you can expect this one to be fixed on 1.0.6
