### ISSUE TITLE
Function to get/set MusicManager (current) pitch.

### ISSUE THREAD

**Issue by lMegoZ** [TeamREPENTOGON/REPENTOGON#304]
Like how there is a `GetSpeedMultiplier()` or a `SetSpeedMultiplier()` function for the Entity class

...but for the MusicManager class.

**Comment by epfly6** [comment]
https://wofsauge.github.io/IsaacDocs/rep/MusicManager.html?#pitchslide

**Comment by epfly6** [comment]
> maybe they meant the exact underlying values? instead of lerping/sliding from previous value to the next the pitch could be set directly

Straightforward set
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/a4f4983c-24d7-4ca3-9064-cdf6f517e235)

**Comment by im-tem** [comment]
thats a target pitch, right? then there has to be current pitch that isnt exposed, isnt that true?

**Comment by lMegoZ** [comment]
I'm more looking for a function that gets the current value of the music's pitch/speed

**Comment by epfly6** [comment]
> thats a target pitch, right? then there has to be current pitch that isnt exposed, isnt that true?

Welp...

![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/1d309498-079f-4559-854f-6e9b16ae1100)

**Comment by epfly6** [comment]
Added in commit https://github.com/TeamREPENTOGON/REPENTOGON/commit/098abe3c4704acde3721f7b80a3971a56583ec26
