### ISSUE TITLE
[Bug] Weapon:SetModifiers() is nil

### ISSUE THREAD

**Issue by Roary0** [TeamREPENTOGON/REPENTOGON#306]
Though it is in the docs, this is what I get running with zero mods (aside REPENTOGON):
![20240131000907_1](https://github.com/TeamREPENTOGON/REPENTOGON/assets/141861144/de4837f5-4747-499f-bef0-3caac503a8c7)

**Comment by wofsauge** [comment]
That feature currently only exists on the github version of the mod and will be added with release v1.0.6. That release will come soon
