### ISSUE TITLE
"Multiple function / variables were not found" error after starting the game"

### ISSUE THREAD

**Issue by hungaryboi14** [TeamREPENTOGON/REPENTOGON#307]
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/103275672/a94e15a4-a994-4c90-974b-87444fd64c27)

**Comment by epfly6** [comment]
What version you have installed? Steam/GOG/EGS?

**Comment by hungaryboi14** [comment]
> What version you have installed? Steam/GOG/EGS?

cracked, cant afford all the game and all the dlcs lmao 
i guess it just doesnt support cracked 😢

**Comment by jsgnextortex** [comment]
It supports version v1.7.9b.J835, it doesnt matter how you get it but you need tht version.

**Comment by hungaryboi14** [comment]
aah, okay thanks

**Comment by imadeagithubaccountforthis** [comment]
does 1.7.9c count?

**Comment by epfly6** [comment]
> does 1.7.9c count?

Not supported, and you are not supposed to have one in first place, since it's unstable

**Comment by imadeagithubaccountforthis** [comment]
unstable??? what the hell do you mean, is it a big scary word to scare people away from pirating?

**Comment by jerbmega** [comment]
No, that patch was withdrawn from Steam because it was buggy and broke controller support among other things. It has nothing to do with piracy.
