### ISSUE TITLE
EntityPickup:IsBlind() returns false even if the pickup is being hidden by the Curse of the Blind question mark graphics

### ISSUE THREAD

**Issue by BadPig03** [TeamREPENTOGON/REPENTOGON#308]
![QQ截图20240201120101](https://github.com/TeamREPENTOGON/REPENTOGON/assets/60381867/a60cc02f-8c24-4e73-b3ea-73ddaf59e034)
From the picture, it's clear that I executed the command `lua for _, item in pairs(Isaac.FindByType(5,100)) do local pickup = item:ToPickup() print(pickup:IsBlind()) end`, but the console printed "false" instead.

**Comment by jsgnextortex** [comment]
This doesnt include curse of the blind currently, it works for stuff thats normally blind without curses involved, like the alt path hidden item, for cases like this, just check fort he curse.

**Comment by BadPig03** [comment]
Thank you for your response. In that case, it would be helpful to indicate it in the documentation or add support for curses.

**Comment by BadPig03** [comment]
> This doesnt include curse of the blind currently, it works for stuff thats normally blind without curses involved, like the alt path hidden item, for cases like this, just check fort he curse.

If you switch the active item on your character while having a curse, the item that is dropped is not hidden. If you solely rely on the curse for judgment, you will get incorrect results. How can this be resolved?

**Comment by jsgnextortex** [comment]
For the time being, Im shoving a disclaimer in the docs, this is not a function we implemented but a vanilla game property of EntityPickup, this is simply how it works in the game, sadly.
As for your particular scenario, you can check the Touched attribute, its true on dropped items.

**Comment by epfly6** [comment]
Updated that method in 9e34642cec86673d3a53d877cde95b4362102f68, so it could return true if blind is applied from the curse
