### ISSUE TITLE
Add method to EntityPlayer that returns the index of the player

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#313]
There's a few instances where a function requires the index of a player, such as the newly added PlayerManager.GetEsauJrState(), however there's no way to get know what index you want without looping through all the players in the game until one of them match the player you're wanting to use. It'd be incredibly convenient for functions like this and some other applications if we could just fetch the index from the player directly.

**Comment by jsgnextortex** [comment]
Made accesible in efc8acf
