### ISSUE TITLE
[Vanilla Bug] Fix Callback Iteration problems caused by the RemoveCallback function

### ISSUE THREAD

**Issue by Guantol-Lemat** [TeamREPENTOGON/REPENTOGON#320]
Whenever the **RemoveCallback** function (be it from the ModReference or the Isaac class) is used to remove a function from a Callback that is currently running, it results in the next callback function not being invoked.

The behavior is the exact same as attempting to use table.remove on a table that is currently being iterated over using ipairs, meaning that the problem only occurs if the function that is being removed has a higher or the same order as the function currently being executed.

To better illustrate this issue, I attached a code snippet demonstrating the problem scenario
[code snippet](https://github.com/TeamREPENTOGON/REPENTOGON/files/14180611/main.lua.txt)

**Comment by ConnorForan** [comment]
Duplicate of https://github.com/TeamREPENTOGON/REPENTOGON/issues/337

**Comment by ConnorForan** [comment]
My apologies, you actually opened this one first, so you win

**Comment by ConnorForan** [comment]
Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/8234c37b67ce104100281a69aa78ce405aaa508a
