### ISSUE TITLE
MC_POST_PLAYER_TRIGGER_ROOM_CLEAR

### ISSUE THREAD

**Issue by thicco-catto** [TeamREPENTOGON/REPENTOGON#321]
We currently have MC_PRE_PLAYER_TRIGGER_ROOM_CLEAR, but we're missing the post version to actually trigger effects.

**Comment by namishere** [comment]
Fixed by [bd7f98a](https://github.com/TeamREPENTOGON/REPENTOGON/commit/bd7f98a011406e3182c81548c7ea8becce53205c)
