### ISSUE TITLE
Entity_NPC::Morph signature not recognized as returning a bool

### ISSUE THREAD

**Issue by namishere** [TeamREPENTOGON/REPENTOGON#327]
LibZHL is unable to find the signature for `Entity_NPC::Morph` if the signature is changed to return a `bool` instead of `void`. This is something that Ghidra also seems to be tripping up on, as it doesn't correctly recognize the `bool` value to return in its pseudo-code Decompile window, but I can verify looking at the asm that `AL` is either xored or set to 1 before the function returns. This prevents me from accurately reimplementing the function for luajit.

**Comment by Sylmir** [comment]
Fixed in https://github.com/TeamREPENTOGON/REPENTOGON/commit/e65c73644aa0f8625065c45c74edbadef151e051

**Comment by namishere** [comment]
OH didn't realize there was a use in CustomCallbacks that expected void, that would certainly do it
