### ISSUE TITLE
EntityPlayer:CancelQueueItem()

### ISSUE THREAD

**Issue by blazeykat** [TeamREPENTOGON/REPENTOGON#328]
Right now the only way to stop a queued item from being added is to use EntityPlayer:FlushQueueItem(), which adds the item to the player's inventory and runs pickup effects, which needs a lot of work arounds to make work properly. An alternative method to this which functions similar to how abyss or void removes a queued item would be very handy and much appreciated.

**Comment by epfly6** [comment]
Added in e7a548135adfdb8bc7f6bbb9b8e43a46d52fc60a, as ``ClearQueueItem``
