### ISSUE TITLE
Character Afterimage

### ISSUE THREAD

**Issue by pokiakjsf** [TeamREPENTOGON/REPENTOGON#329]
when i play with repentogon, my character leaves frames like an afterimage

**Comment by pokiakjsf** [comment]
it is the trail of sprites and also i have a problem that i dont know if its related but i cant touch the walls or obstacles, i bounce off them and i deal contact damage to everything without losing health

**Comment by jsgnextortex** [comment]
Sorry, but I extremely doubt this is caused by repentogon alone, I'd suggest you to disable your mods and see if you can find the actual root of the issue.

**Comment by pokiakjsf** [comment]
you were right, it was the epiphany mod

**Comment by Jujulues** [comment]
pokia, can you submit this issue here?
https://github.com/OpenSauce04/EpiphanyIssues
If this is an epiphany issue I want to see what could be causing it.
