### ISSUE TITLE
Eden's Blessing Item causing intermittent crashes upon run restarts

### ISSUE THREAD

**Issue by Crab0n** [TeamREPENTOGON/REPENTOGON#341]
Eden's Blessing:
+0.7 tears up.
Grants a random item at the start of the next run.

Fails to award a new item at start of next run and sometimes crashes when restarting.

"MC_POST_GAME_STARTED" from "Epiphany" failed: attempt to index a nil value
Stack Traceback:
  in method for iterator
  .../epiphany_3012430463/scripts/helpers/table_functions.lua:187: in function 'Set'
  ...any_3012430463/scripts/epiphany/characters/eden/eden.lua:122: in function at line 90

**Comment by jsgnextortex** [comment]
This is the git for Repentogon not Epiphany, try to bring this up to them

**Comment by OpenSauce04** [comment]
@Crab0n If you don't mind, could you create an issue about this in https://github.com/OpenSauce04/EpiphanyIssues?

I'd like to investigate this issue further
