### ISSUE TITLE
Horse pills and golden trinkets are missing from the console's autocomplete

### ISSUE THREAD

**Issue by Cuerzor** [TeamREPENTOGON/REPENTOGON#356]
You could give player a horse pill via "g P[number]", or golden trinket via "g T[number]" in vanilla game, but in Repentogon you can't.

**Comment by im-tem** [comment]
Guess how many of RGON's developers knew about this feature 😅

**Comment by im-tem** [comment]
By the way, the functionality itself is available, only the autocomplete part is missing

**Comment by jsgnextortex** [comment]
Yea, remember the console still calls the vanilla console functions on the backend so anything that works in vanilla will work here....autocomplete is another story, since thats completely reimplemented. NOW, yea, Im not even going to try and deny it, none of us knew this shit even existed, lol.
