### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by AverageCisaacEnjoyer** [TeamREPENTOGON/REPENTOGON#358]
Hi Rep team, hope you are all doing well on this week-end. I just wanted to tell you abt an issue I got recently while trying to put Repentogon on my friend cracked version so he could use some mods and more on utility mods that I do have in-game to have a better experience of Tboi. When we tryed to launch the game after repantogon installer told us it was finished, the game said that there was missing variables. I do not know what that means precisely so I hope you could help us with that. Have a great week-end.

**Comment by im-tem** [comment]
Variables/signatures not found = wrong version of the game, read the home page and make sure your version matches that EXACTLY

**Comment by epfly6** [comment]
REPENTOGON only supports version v1.7.9b.J835

**Comment by AverageCisaacEnjoyer** [comment]
> REPENTOGON only supports version v1.7.9b.J835

Can we install previous versions of this script extender ?

**Comment by jerbmega** [comment]
No. We've never supported versions other than v1.7.9b.J835 and this will not change any time soon.

**Comment by AverageCisaacEnjoyer** [comment]
Thanks alot for everything guys.
