### ISSUE TITLE
XMLData List for each NodeType

### ISSUE THREAD

**Issue by popjam** [TeamREPENTOGON/REPENTOGON#361]
A function that returns a table of entries given a NodeType

Suggested it on the discord but I'll add it here, it'd be a massive help for the deleted 2.0 and I think other mods could use it too (e.g encyclopedia mods)

**Comment by jsgnextortex** [comment]
107 adds GetNodeByuOrder which facilitates iterating through xml files in combination with GetNumEntries, so this is not needed. Without mentioning, it would be freaking insane to push entire xmls in a single go to the lua side (specially those line the entities.xml).
