### ISSUE TITLE
Issue abt launching runs

### ISSUE THREAD

**Issue by AverageCisaacEnjoyer** [TeamREPENTOGON/REPENTOGON#366]
Sorry it's my second time about issues , particularly about launching. I was trying mods that added content like Revelation chapter 2 , Epiphany and some characters. Now about launching game I can lanch it without problem it is about the Epiphany char selection menue. When I try to launch it to select Tarnished characters I have an error message saying that my game is missing files and I got a basement 1 black isaac with a red question mark on it's body then my game crash with and error simimar to when u got wrong version for Repentogon script extend. This is why I am contacting you sorry for bothering you.

**Comment by AverageCisaacEnjoyer** [comment]
I got a second question there, what's the difference between 1.7.9b and 1.7.9b.j835?

**Comment by jsgnextortex** [comment]
REPENTOGON needs version v1.7.9b.J835, the difference is that....the exe is different, thats all that matters, this is an exe mod.
