### ISSUE TITLE
MC_POST_RENDER_PLAYER_HEAD/BODY

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#369]
Simple POST versions of the MC_PRE_RENDER_PLAYER_HEAD/BODY callbacks. Would be handy for needing to render something specific for every copy of the head and body being rendered that obeys if its stopped by their PRE callbacks, during player's flashing on i-frames, or other use-cases.

**Comment by jsgnextortex** [comment]
Done cea1d79
