### ISSUE TITLE
EntityPlayer:GetFamiliar(variant, subtype = -1)

### ISSUE THREAD

**Issue by Foks256** [TeamREPENTOGON/REPENTOGON#379]
A function that would return the wanted familiar entity, there could also be an alternative function for multiple familiars.

**Comment by im-tem** [comment]
sounds kinda backwards to how it works, arent you supposed to run familiar code in familiar entity callbacks? can you provide any good usage example?

**Comment by Foks256** [comment]
> sounds kinda backwards to how it works, arent you supposed to run familiar code in familiar entity callbacks? can you provide any good usage example?

Hmm, what about if I wanted to change a familiar when using an active item? MC_USE_ITEM already provides the player argument and doing a for loop of familiars just to get that specific player seems wrong idk

Or if I wanted to get the familiar from a player callback that already provides the player in general

**Comment by jsgnextortex** [comment]
FindByType Exists
