### ISSUE TITLE
New version has troubles with save files

### ISSUE THREAD

**Issue by Anrixxen** [TeamREPENTOGON/REPENTOGON#387]
so after updating repentogon to 1.0.8 I logged into isaac to see all my save data gone. I didn't really want to have my 300+ hours wasted on nothing, so i started trying to restore my save somehow. went into the game files and found this
![изображение_2024-03-24_203521040](https://github.com/TeamREPENTOGON/REPENTOGON/assets/139979760/7bf55469-c5d4-44bf-bd36-13f01936aba4)
the lower 3 files are from before updating repentogon and the upper three are after

after i got rid of the upper three, I launched the game again, and 3 new date_persistentgamedata.dat appeared. got no screenshot cause im lazy and forgot
after a few minutes of bashing my head against the keyboard and hoping for the best, i had a moment of clarity and revelation, bestowed upon me by deities beyond my understanding (i copied the files before repentogon update and renamed them into normal persistentgamedata.dat) and all my save data appeared again. 

now i don't really know how isaac's save system works, but is it possible for repentogon to just erase your save data in the files? it could also be a me problem, but just in case it isn't, im writing this.

**Comment by epfly6** [comment]
Have you tried to restart steam and launch game again?

**Comment by jsgnextortex** [comment]
Absolutely nothing changed in regards to savefiles and repentodon does absolutely nothing to alter there, this must be an issue with steamcloud or something of the sorts.
