### ISSUE TITLE
Installer fails to install

### ISSUE THREAD

**Issue by TerraWispr** [TeamREPENTOGON/REPENTOGON#389]
An update notification came up when I launched Isaac, the installer popped up as usual but it failed to locate the update. Also occurs when directly launching the installer.

Error message:
`
Fetching latest release from GitHub...
Fetching hash...
Failed to install!
Invalid URL '' : No scheme supplied. Perhaps you meant https://?
`

**Comment by namishere** [comment]
New hash.txt failed to upload, was just fixed; try again
