### ISSUE TITLE
Suggestion: Add new items.xml tag "nometronome"

### ISSUE THREAD

**Issue by CatbunnyAeronaut** [TeamREPENTOGON/REPENTOGON#390]
Metronome can activate the effect of hidden tagged modded items, which can be a bit unfair if it just so happens to proc one of these items that are made as a joke or utility purposes. Since there are some vanilla items that can't be triggered by Metronome, I feel like this would be a good opportunity to allow modders to expand this blacklist to items with those purposes.

**Comment by epfly6** [comment]
Added in a680057, f245660
