### ISSUE TITLE
suggestion: a method for getting/setting the delay between being able to place bombs

### ISSUE THREAD

**Issue by An-Annoying-Cat** [TeamREPENTOGON/REPENTOGON#392]
both the max delay and the current delay, like how it is for fire rate

**Comment by im-tem** [comment]
max delay is scoped entirely within the bomb controls function, its not a field value anywhere
current delay, however, was identified and will be exposed to the api soon

**Comment by im-tem** [comment]
EntityPlayer:Get/SetBombPlaceDelay was implemented in 26591a1962111eeac429fb008559d1bb30b4dc2a and will become available in the next release
![2024-03-2918-00-40-ezgif com-video-to-gif-converter](https://github.com/TeamREPENTOGON/REPENTOGON/assets/18075164/6d7e339a-97c5-4e37-9112-18d5be55375d)
