### ISSUE TITLE
Better Fullscreen Support?

### ISSUE THREAD

**Issue by SmashKid15** [TeamREPENTOGON/REPENTOGON#398]
What I'm asking for is easier siad than done. but it's worth trying to request it.
A new config of Fullscreen mode that allows users to customise the lengh and width to match their set-up and preference.
Go from this...
![One](https://github.com/TeamREPENTOGON/REPENTOGON/assets/163786982/e92c3c8a-dab5-42da-8ab3-0e726909a88a)
To this...
![Two](https://github.com/TeamREPENTOGON/REPENTOGON/assets/163786982/eddea4f7-3b8d-47d4-8a04-73fec8918a07)
(aware of the diffrences of the picture, had to debug to match it one-one somewhat.)

**Comment by epfly6** [comment]
Imgui bar -> Game Options -> Visual Effects -> Set Max Scale to minimum
