### ISSUE TITLE
EntityTear::ResetSpriteScale() not updating size animation when a size anim is played manually

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#400]
Function is supposed to "Reset the tear sprite animation depending on scale." but it seems to always be resetting to its default animation no matter what. This is a vanilla issue, not RGON. Would be nice to have this fixed.

**Comment by Sanio46** [comment]
Spoke to @ConnorForan and turns out that the precise issue with this function is not related to this function at all. Tears internally keep track of the size animation number as an integer instead of checking against the current animation, which determines when it should update its animation when the scale changes. This is why forcing a tear size anim on a tear won't update unless its scale is updated. Connor said they'd possibly expose something related to this.

In the meantime, I found that forcing a small scale, calling ResetSpriteScale, changing it back to its original scale, and calling the same func, works fine.

**Comment by ConnorForan** [comment]
Added an optional "force" boolean to ResetSpriteScale in https://github.com/TeamREPENTOGON/REPENTOGON/commit/8adaf805a418cdcdf554b64513cca31d86e695bb 

So with `tear:ResetSpriteScale(true)`, it will always attempt to correct the animation
