### ISSUE TITLE
repentogon installer trouble

### ISSUE THREAD

**Issue by animeslayer224** [TeamREPENTOGON/REPENTOGON#405]
i'm probably doing things wrong it says i have to add the installer to the games directory to use install the installer i don't know how to do that and the steps weren't very clear on doing how to do that at least to me

**Comment by jsgnextortex** [comment]
It also isnt very clear on this message on whats not very clear to you on how to install the installer added to the games directory folder.
But, yea, you have to either copy the installer to the game directory (where the exe for the game is) and then run it...or copy the manual instalation files there. If thats too complex for you then this mod may simply not be for you at its current state.
