### ISSUE TITLE
Rendering multiple animations with one Sprite object?

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#410]
This is something not terribly knowledgeable about but only have observed in-game so bare with me here. I've seen examples of sprites we've been given access to thanks to RGON such as the character select menu, nightmare scene, and minimal icons, all have the ability to be one Sprite object but render multitude of animations. The only way to achieve something like this ourselves is an abomination of stacking a ton of layers on one animation and using Sprite:Render layer to render them all separately.

Minimap Icons anm2. It has a ton of different animations, one for each icon
![image-46](https://github.com/TeamREPENTOGON/REPENTOGON/assets/7707552/dbd8755b-b162-4c90-9edf-81d9b22cd133)

Gross anm2 I had to create to somewhat replicate this. I use Sprite:RenderLayer to render each icon and change frames on that layer, since I only need one on each layer active at a time.
![image-40](https://github.com/TeamREPENTOGON/REPENTOGON/assets/7707552/9482f00a-a133-4d26-9539-ad4101c45c85)

This would be a great feature to have, assuming I'm guessing how this functions correctly.

**Comment by jsgnextortex** [comment]
I dont get what feature are you requesting here tbh...

**Comment by ConnorForan** [comment]
I believe the assumption is that the game had some utility for rendering multiple animations from an ANM2 simultaneously, but given how the ANM2/Sprite class works, I'm pretty sure the game is just changing the animation repeatedly

A glance at MiniMap::render_icons() in ghidra seems to support this, it has a loop where it calls SetAnimation/SetFrame/Render etc

**Comment by Sanio46** [comment]
In my head with complete assumption without testing it out, I thought changing animations on the same sprite object would affect all current renders of the sprite at the same time, even though that's not how it works. Just something that stuck in my head and I was curious how the game does it. I have a tendency to have an obsession to replicate my own code as closely as to how the game functions as possible. I appreciate the reassurance though and I'll just be changing animations as I render my sprites.
