### ISSUE TITLE
Custom GridRooms

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#412]
Currently, there's only so many GridRooms (rooms that don't exist on the map, like a Devil or Angel Deal) that exist, and so many that other mods can override for their own custom GridRoom. Having the ability to create custom GridRooms would be amazing so we don't have to carefully tiptoe around what GridRooms we can override or not.

**Comment by Sylmir** [comment]
This will be difficult as the game uses a finite sized array to store negative rooms

**Comment by Sanio46** [comment]
I'm aware of this, and this is me purely speaking from lack of experience, but the enum GridRooms.MAX_GRID_ROOMS suggests that there's at least a pretty sizable amount of finite space? Or is it much more limited?

**Comment by Sanio46** [comment]
Taking two seconds to read the other enum MAX_OFF_GRID_ROOMS, it's 18.

**Comment by jsgnextortex** [comment]
The only way we would add stuff like this is is if it was limitless, theres no point in adding functionality that only 1-2 mods will be able to use at once at the end of the day

**Comment by Sylmir** [comment]
One thing that might be worth is adding the ability to load any RoomConfig Room in a RoomDescriptor, as well as more control to save / restore RoomDescriptors

**Comment by jsgnextortex** [comment]
Definitely
