### ISSUE TITLE
MC_PRE_X_UPDATE

### ISSUE THREAD

**Issue by Lunastela** [TeamREPENTOGON/REPENTOGON#416]
It would be great to be able to access tear and laser updates in order to cancel them. May look into this myself, but I figured I'd make an issue for it in case it's useful to anyone else as well.

**Comment by ConnorForan** [comment]
I was looking into making pre-callbacks for all entity types where it is missing recently, there was just a minor issue to sort out, but ill get back to it soon enough

**Comment by Lunastela** [comment]
Thank you so much!

**Comment by ConnorForan** [comment]
Added in https://github.com/TeamREPENTOGON/REPENTOGON/commit/ba6d2d7fa4ca9bd0cc2fcfd44948efe49bc65a67, will be available next update
