### ISSUE TITLE
MC_PLAYER_GET_ACTIVE_MIN_USABLE_CHARGE - needs player param

### ISSUE THREAD

**Issue by nazardz** [TeamREPENTOGON/REPENTOGON#424]
if it's possible this callback need player function arg, rn it provides only active item slot

**Comment by epfly6** [comment]
It does, just not mentioned in docs 
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/36567300/12077d10-3925-4373-adb1-d0caa2efe139)

**Comment by epfly6** [comment]
Fixed d5702361
