### ISSUE TITLE
Slow restart with Repentogon enabled

### ISSUE THREAD

**Issue by ivanovishado** [TeamREPENTOGON/REPENTOGON#430]
Hi, folks. Thanks for the amazing mod.

While holding the 'R' key, the restart is way slower than it was on vanilla Repentance. Could you please check that out?

TIA.

**Comment by im-tem** [comment]
which part of it is slower? the fadeout? the restart itself (delay after full fade and before you see the restarted run)?

**Comment by ivanovishado** [comment]
Yeah, the restart itself. If I hold down 'R' on vanilla it starts resetting quickly. But this doesn't happen with Repentogon enabled.

**Comment by im-tem** [comment]
so is it stuck on the black or what??

**Comment by ivanovishado** [comment]
It's not stuck in the black. The restart completes successfully, it just feels much slower than without Repentogon enabled.

I'll try recording a video later.

**Comment by ivanovishado** [comment]
Just tested again and seems that it's because another mod. Closing this issue.
