### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by nomaryda** [TeamREPENTOGON/REPENTOGON#432]
Even if I update it, it says it's not all installed. It's the same even if I try it manually.

**Comment by namishere** [comment]
Can you copy & paste the directory you're unpacking the files into? (ie `C:/Program Files (x86)/Steam/steamapps/common/The Binding of Isaac Rebirth`)

**Comment by nomaryda** [comment]
C:\Program Files (x86)\Steam\steamapps\common\The Binding of Isaac Rebirth
This is the configuration.

**Comment by nomaryda** [comment]
I've found the cause. It comes with a program called "Ocam." It's a recording program, and I don't know why it pops up.
