### ISSUE TITLE
Game crashes while having controller as main input device and when selecting mods tab in menu

### ISSUE THREAD

**Issue by iksperius** [TeamREPENTOGON/REPENTOGON#434]
Game crashes when trying to use controller (xbox series controller) in menu, clicking anything instantly crashes game, on keyboard game works normally. But I can join game while on keyboard, and play as co op player on controller.
Same thing happens when trying to join game on keyboard, and changing input device to controller, game instant crashes while trying to do anything
Game also crash when trying to select mods tab in menu
[log.txt](https://github.com/TeamREPENTOGON/REPENTOGON/files/15170903/log.txt)

**Comment by jsgnextortex** [comment]
Restart your PC, do not turn off, restart...then it should be fixed.

**Comment by iksperius** [comment]
I feel ashamed that it was that simple, everything works
