### ISSUE TITLE
Access to Hallowed Ground / Star of Bethlehem aura timeout

### ISSUE THREAD

**Issue by TaigaTreant** [TeamREPENTOGON/REPENTOGON#436]
When the player exits the aura of Hallowed Ground poops, Star of Bethlehem and other similar effects, the effects of the aura do not immediately disappear. Instead, they linger on the player for about 4 update frames before disappearing. This implies that somewhere the game is storing a timeout variable for this effect as part of the EntityPlayer class. It would be good to expose this value, for the purposes of allowing easier handling of the corresponding damage/tears multiplier, as well as to allow adding new items that utilize this effect.

**Comment by kittenchilly** [comment]
Added!
