### ISSUE TITLE
Access to Tainted Eve's passive Sumptorium clot spawning charge

### ISSUE THREAD

**Issue by TaigaTreant** [TeamREPENTOGON/REPENTOGON#437]
When Tainted Eve is firing, she passively builds up a chargebar that spawns a Sumptorium clot familiar when filled. Currently, there is no way to access this charge value, which is an issue if you want to modify this effect (such as disabling it on a custom 1hp heart when it is the only such heart the player has). It would be helpful if this value could be exposed.

**Comment by epfly6** [comment]
Isn't it exposed already as https://repentogon.com/EntityPlayer.html?#getevesumptoriumcharge?

**Comment by TaigaTreant** [comment]
Ah, shoot. Must've missed that.
