### ISSUE TITLE
Downpour rooms in the void do not have water

### ISSUE THREAD

**Issue by oilyspoily** [TeamREPENTOGON/REPENTOGON#439]
Downpour and Dross rooms in Void are waterless.
![2024-05-03 07-21-24](https://github.com/TeamREPENTOGON/REPENTOGON/assets/50062278/ec022504-8824-4257-9ef5-e401116b0ec3)
![2024-05-03 07-22-05](https://github.com/TeamREPENTOGON/REPENTOGON/assets/50062278/c4fec387-5b20-4d9b-988f-686d4b3b295f)
![2024-05-03 07-06-48](https://github.com/TeamREPENTOGON/REPENTOGON/assets/50062278/10bd0ba3-ca20-4ae3-834f-b3e9587ffb74)
![2024-05-03 07-26-09](https://github.com/TeamREPENTOGON/REPENTOGON/assets/50062278/978e67b5-6102-4357-b3c3-d5148a046000)

I wonder how feasible this is to fix, I recall it being a very hard issue to fix, perhaps unfixable.
Flooded Caves and Corpse rooms in Void have water, so I wonder if that can be looked at for a potential solution?

**Comment by Sylmir** [comment]
I'm assuming the game has special checks on the current floor in order to determine whether the room should have water / current, probably needs an ASM patch when the game loads the room. Like many other things, it's been on my todo list for a while now :(

**Comment by oilyspoily** [comment]
don't worry sylmir i am a patient little thingy

**Comment by namishere** [comment]
Fixed in 8bbbdce3
