### ISSUE TITLE
Repentagon wont work. Getting a frozen white screen on start up and cant find an answer anywhere

### ISSUE THREAD

**Issue by JereKane** [TeamREPENTOGON/REPENTOGON#442]
Tried everything I could think of and Isaac refuses to load unless I uninstall repentagon. I've tried installing it with no workshop mods on, with them on, one by one, installing the files in different folders in game directory, manual and automatic install, nothing. No error message or anything, just a white screen

![Screenshot 2024-05-09 214137](https://github.com/TeamREPENTOGON/REPENTOGON/assets/169415711/fae74565-590e-4162-aaa9-67dc5aee717c)

**Comment by JereKane** [comment]
> Try disabling autoupdates on dsound.ini if that doesnt work, given your circumstances, it may be that your system is not compatible with dsound.

Ahhhh, that makes sense now. I figured it was some update issue

Do I just delete this line ([INFO] [2024-05-09 21:40:35] dsound: Checking for updates) or type something in place of it?

**Comment by namishere** [comment]
> > Try disabling autoupdates on dsound.ini if that doesnt work, given your circumstances, it may be that your system is not compatible with dsound.
> 
> Ahhhh, that makes sense now. I figured it was some update issue
> 
> Do I just delete this line ([INFO] [2024-05-09 21:40:35] dsound: Checking for updates) or type something in place of it?

Wrong file, look for dsound.**ini** and create it if it doesn't exist

**Comment by JereKane** [comment]
> Wrong file, that's dsound.**log**. look for dsound.**ini** and create it if it doesn't exist


I kinda hate being a bother, but would you happen to have a screenshot of what it looks like? I can screen record the issue I keep running into

**Comment by jsgnextortex** [comment]
No need, you did it yourself, it appears on your own screenshot, lol

**Comment by JereKane** [comment]
> No need, you did it yourself, it appears on your own screenshot, lol If you mean the content, you'll know what to do when you open it, should look like this: [Options] CheckForUpdates = 0
> 
> [internal] RanUpdater = 0

[A video link of generally what happens.](https://streamable.com/1t6hmt) Clicking on the only openable dsound file brings up the log, so somehow or another the options listed below this comment aren't anywhere to be found

**Comment by jsgnextortex** [comment]
Add them then, copypaste this isnide of the dsound.ini you created:
[Options]
CheckForUpdates = 0

[internal]
RanUpdater = 0

**Comment by JereKane** [comment]
> Add them then, copypaste this isnide of the dsound.ini you created: [Options] CheckForUpdates = 0
> 
> [internal] RanUpdater = 0
> 
> Also, try to wait more than 2s for the game to launch, you seemed to close it way too fast in the video, I assume you did wait longer on other attempts but Im clarifying it just in case.

I found out I was a damn idiot lol

I 100% followed your instructions, but what I kept doing was saving dsound as txt, then going back and renaming the file as dsound.ini. Tried it again today and randomly decided to hit "Save As > Dsound.ini" instead and now it works -____-

**Comment by MicroVirus123** [comment]
> Try disabling autoupdates on dsound.ini if that doesnt work, given your circumstances, it may be that your system is not compatible with dsound.

how do i access dsound.ini as i have the same issue
