### ISSUE TITLE
PRE/POST_POCKET_ITEM_ADD/DROP

### ISSUE THREAD

**Issue by Sanio46** [TeamREPENTOGON/REPENTOGON#444]
Callbacks for when a new PocketItem is added to your inventory (card, pill, active item) and for when it's dropped. PRE callbacks could prevent it from being added/dropped if possible.

**Comment by ConnorForan** [comment]
https://github.com/TeamREPENTOGON/REPENTOGON/commit/4ccb96d1f3ef8e96dfd070f6017cd4cf7c94266f
