### ISSUE TITLE
EntitySlot:GetTimeout() and :SetTimeout() interact with DonationValue

### ISSUE THREAD

**Issue by S0meEngineer** [TeamREPENTOGON/REPENTOGON#452]
- `EntitySlot:GetTimeout()` returns timeout with added value of `(1<<16) * EntitySlot:GetDonationValue()`
- `EntitySlot:SetTimeout()` affects `DonationValue` in a similar way

  - Lua workarounds are:
    `local timeout = slot:GetTimeout() % 65536`
    `slot:SetTimeout(timeout + 65536 * slot:GetDonationValue())`

![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/167571242/9668750b-a108-4ac7-bf36-5c44d6e631d3)

**Comment by epfly6** [comment]
Should be fixed (6c3322b5cfbd6563c1848a1ce266a37cb76827e1)
