### ISSUE TITLE
PRE_SET_COLOR

### ISSUE THREAD

**Issue by guwahavel** [TeamREPENTOGON/REPENTOGON#457]
Runs whenever [Entity:SetColor()](https://wofsauge.github.io/IsaacDocs/rep/Entity#setcolor) is called with Color, Duration, Priority, Fadeout, and Share parameters. A table with any of those parameters can be returned to override them.

This is useful for reskinning enemies for custom stages and making them flash more appropriate colors. Overriding vanilla uses of SetColor is very difficult/bad-looking otherwise.

**Comment by Syntax-Sculptor** [comment]
Duplicate of #332
