### ISSUE TITLE
Incorrect documentation for EntityPickup:GetPickupGhosts() and EntityPickup:UpdatePickupGhost()

### ISSUE THREAD

**Issue by BadPig03** [TeamREPENTOGON/REPENTOGON#478]
The documentation for EntityPickup:GetPickupGhosts() and EntityPickup:UpdatePickupGhost() are still incorrect!
The correct version is EntityPickup:GetPickupGhost() and EntityPickup:UpdatePickupGhosts().
![QQ截图20240608095315](https://github.com/TeamREPENTOGON/REPENTOGON/assets/60381867/4715a0bf-12a3-4554-92b6-a8e7894b5ca5)

**Comment by epfly6** [comment]
Head up to https://github.com/TeamREPENTOGON/REPENTOGON/issues/474 and do not create duplicates
