### ISSUE TITLE
It keeps loading while running and is stuck on the start screen...

### ISSUE THREAD

**Issue by KonglanNyn** [TeamREPENTOGON/REPENTOGON#492]
![屏幕截图 2024-06-27 141437](https://github.com/TeamREPENTOGON/REPENTOGON/assets/102920176/280dae3e-403a-48b2-a65e-b7bf46386ce8)
Yesterday I upgraded my computer to win11 Then try to open the game and that's it

I tried to remove all the mods and found out that this new mod was causing it to keep loading。
Disable it and you're good to go 

Doesn't this mod work on win11?

**Comment by epfly6** [comment]
Post .log and dsound.ini files on games folder

**Comment by KonglanNyn** [comment]
No found Post.log but found dsound.ini
![image](https://github.com/TeamREPENTOGON/REPENTOGON/assets/102920176/7423e0a6-a792-4c35-80ea-8b7b5aa8444b)

**Comment by KonglanNyn** [comment]
I'm sorry I don't know why it suddenly works again。I reloaded it

**Comment by KonglanNyn** [comment]
Is this what you're talking about?
[dsound.log](https://github.com/user-attachments/files/16011660/dsound.log)

[repentogon.log](https://github.com/user-attachments/files/16011705/repentogon.log)

[sig_008720b8.log](https://github.com/user-attachments/files/16011707/sig_008720b8.log)

[zhl.log](https://github.com/user-attachments/files/16011709/zhl.log)

**Comment by KonglanNyn** [comment]
Solved the problem, same as this one
https://github.com/TeamREPENTOGON/REPENTOGON/issues/409
I deactivated CheckForUpdates and it worked

**Comment by epfly6** [comment]
> Solved the problem, same as this one #409 I deactivated CheckForUpdates and it worked

Github is blocked in China, so updater can't fetch files for repentogon
