### ISSUE TITLE
Not working on CrossOver for macOS

### ISSUE THREAD

**Issue by yeiyieayi** [TeamREPENTOGON/REPENTOGON#494]
Everything worked and installed perfectly in CrossOver, but when i run isaac i still get the "not installed" error

also, when i use the "WINEDLLOVERRIDES=dsound=n,b %command%" command on steam, the game wont launch at all.

using crossover 24, macOS sonoma

maybe it requires a different command? im willing to do tests

**Comment by namishere** [comment]
Likely fixed by a9fd334
