### ISSUE TITLE
REPENTOGON.MeetsVersion always returns true

### ISSUE THREAD

**Issue by Cuerzor** [TeamREPENTOGON/REPENTOGON#496]
![QQ截图20240702151551](https://github.com/TeamREPENTOGON/REPENTOGON/assets/22266114/37f6af77-6df6-4997-b3ec-00eb8c1fb674)
![QQ截图20240702151630](https://github.com/TeamREPENTOGON/REPENTOGON/assets/22266114/50f1da51-647c-4f92-816f-2cb47fa947f1)

**Comment by Sylmir** [comment]
Issue comes from appveyor.yml replacing all occurrences of "dev build" with the new version when a release is performed. Shouldn't be too hard to fix
