### ISSUE TITLE
Add ItemChargeType to the documentation 

### ISSUE THREAD

**Issue by rageTrash** [TeamREPENTOGON/REPENTOGON#500]
request to add the the item charge types to the documentation

**Comment by ConnorForan** [comment]
Do you mean the ways active items gain charges, as in `ItemConfig.CHARGE_NORMAL`, `ItemConfig.CHARGE_TIMED` and `ItemConfig.CHARGE_SPECIAL`? (Already exists @ https://wofsauge.github.io/IsaacDocs/rep/enums/ItemConfig.html)

Or something different?

**Comment by rageTrash** [comment]
sorry is was kinda hidden

**Comment by ConnorForan** [comment]
No worries, it has always been a little odd that there's a few different enums under "ItemConfig" instead of their own enums

**Comment by rageTrash** [comment]
is confusing why they're 2 different ItemConfig
