### ISSUE TITLE
Repentogon abruptly stopped functioning, no longer loads/installs

### ISSUE THREAD

**Issue by Lolkat76** [TeamREPENTOGON/REPENTOGON#522]
For whatever reason now, Repentogon simply will not load when starting the game. I'm fairly certain there weren't any updates to Isaac as the modding discord likely would've been in a bit of an uproar, and I had it working functionally just a day prior, but now it simply does not load when launching the game (no .log files, no title bar, either).
I have tried:
- reinstalling Repentogon
- uninstalling and reinstalling Repentogon
- uninstalling and reinstalling Isaac itself, then reinstalling Repentogon
- installing Repentogon & launching the game as administrator
- disabling the check for updates field in dsound.ini (i saw that fixed things for some but not me)

Additional details just in case they help:
- last run I completed was a Tainted Blue Baby run vs. the Beast, won, and then I closed the game (next launch it didn't load anymore)
- the only Lua mod I have that updated in the time that I had enabled was Soundtrack Menu (which I'm pretty sure doesn't matter given load order but..)
- I have been back-and-forthing the game a lot with enabling and disabling mods and the debug console in the options.ini because I've been working on grinding the daily challenge achievements in between other achievements, but I've been doing this for a week now with no issue

OS & Hardware information because I know that's handy:
Processor	AMD Ryzen 7 2700X Eight-Core Processor            3.70 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	22H2
OS build	19045.4651
Experience	Windows Feature Experience Pack 1000.19060.1000.0
Graphics Card -> NVIDIA GTX 1070 TI

Any further info needed for solving things, I gotchu, just ask away

**Comment by jsgnextortex** [comment]
When you say that it doesnt load you mean that the game loads without repentogon or that you are stuck in a white/black screen?
If its the former, did you perform any kind of driver/OS updates recently?

**Comment by Lolkat76** [comment]
Well, it randomly started working again? Not sure why but... I suppose that makes the issue solved?
I'm blaming it on the programming phenomenon of "the minute I ask for assistance everything works again and I look silly"

**Comment by Lolkat76** [comment]
> When you say that it doesnt load you mean that the game loads without repentogon or that you are stuck in a white/black screen? If its the former, did you perform any kind of driver/OS updates recently?

It was the former, it could've been a recent bluescreen and it might've made things messy
