### ISSUE TITLE
AddEntityFlags no longer works correctly without setting an appropriate Countdown beforehand

### ISSUE THREAD

**Issue by MrSeemsGood** [TeamREPENTOGON/REPENTOGON#534]
Previously in base API, `Entity:AddEntityFlags(EntityFlag.FLAG_FREEZE)` would permanently freeze the enemy until `ClearEntityFlags` is used. This no longer seems to be the case in RGON. When you just add the entity flag, the enemy almost instantly gets unfrozen. To keep the enemy frozen for a certain duration, it seems calling `SetFreezeCountdown(s:int)` is necessary before adding the flag, and then setting that countdown to 0 to unfreeze the enemy.

CBA to test how this works for other status effects. Willing to create a pull request with appropriate changes in documentation if this is confirmed.

**Comment by epfly6** [comment]
> Previously in base API, Entity:AddEntityFlags(EntityFlag.FLAG_FREEZE) would permanently freeze the enemy until ClearEntityFlags is used. This no longer seems to be the case in RGON. When you just add the entity flag, the enemy almost instantly gets unfrozen.

We have not changed the behaviour of AddEntityFlags method, just in case. 

And here's my footage's where I apply AddEntityFlags(EntityFlag.FLAG_FREEZE) on Gaper without and with Repentogon

https://github.com/user-attachments/assets/4c943e68-6fcf-4c2f-92fb-d706ef2ef779


https://github.com/user-attachments/assets/e93311d9-cdb0-40a0-9afc-6e3c0bf66a36

Basically the same behaviour, freeze, but with a delay then the status is removed. So I would like to ask your code for reproduction, or trying to run it yourself with repentogon

**Comment by MrSeemsGood** [comment]
That's a mistake on my part, apologies. Indeed, after checking it doesn't work in the base game either, though I was certain it did.
