### ISSUE TITLE
COUNTERFEIT_PENNY enum should be 64

### ISSUE THREAD

**Issue by laceous** [TeamREPENTOGON/REPENTOGON#535]
https://github.com/TeamREPENTOGON/REPENTOGON/blob/main/repentogon/resources/scripts/enums_ex.lua

https://repentogon.com/enums/Achievement.html

```
COUNTERFEIT_COIN = 64, COUNTERFEIT_PENNY = 65,
GUPPYS_HAIRBALL = 65,
```

COUNTERFEIT_PENNY appears to be set to GUPPYS_HAIRBALL enum value. I'm assuming this was a typo.

**Comment by im-tem** [comment]
fixed in eb8f3ba
