### ISSUE TITLE
MC_PRE_PLAYER_ADD_HEARTS does not trigger for bone hearts

### ISSUE THREAD

**Issue by TaigaTreant** [TeamREPENTOGON/REPENTOGON#564]
The `MC_PRE_PLAYER_ADD_HEARTS` callback does not seem to be triggered for any bone hearts, whether they be from pickups, items like Marrow, or directly from the `EntityPlayer:AddBoneHearts()` function.

**Comment by epfly6** [comment]
Duplicate #373
