### ISSUE TITLE
Fix the Pathfinder Methods

### ISSUE THREAD

**Issue by Syntax-Sculptor** [TeamREPENTOGON/REPENTOGON#566]
## Problem

The Pathfinder class has always been frustrating to use as many of the methods in the class are bugged. This issue in particular mainly concerns `FindGridPath` as it's the game's intended way to handle entities moving to their target.

Right now, calling `FindGridPath` causes entities to navigate around solid grid objects blocking their target as intended. However, once the target is directly in their line of sight, the entity cheeses to only move ordinarily towards the target. The entity also does not end up being able to completely reach the target.

The fourth argument in the method, `useDirectPath`, suggests that the entity will move *directly* towards the target if it's in their line of sight. However, the argument seems to do nothing.

To illustrate the issue, here is a video: 

https://github.com/user-attachments/assets/e5d661b1-94cb-44b9-a60d-197ea7457e99

Code snippet:

```lua
local targetPosition = npc:CalcTargetPosition(0)
npc.Pathfinder:FindGridPath(targetPosition, 0.5, 900, true)
```

## Current Solutions

Historically, modders had to work around this issue by writing their own pathfinding systems that uses a combination of `Room:CheckLine`, setting the npc's velocity directly, and calling `Pathfinder:FindGridPath`. This does pose some challenges which can be annoying, such as:

- You cannot use the same length used with the resized velocity vector in `Pathfinder:FindGridPath`, you will need to either play around with the speed argument until it's just right or derive your own formula to convert it. To illustrate:

```lua
local speed = 6
npc.Velocity = (targetPosition - npc.Position):Resized(speed) -- Okay. Moves a little slow.
npc.Pathfinder:FindGridPath(targetPosition , speed, 900, true) -- Now the NPC moves at light speed.
```

- Modders have to implement their own fear and confusion AI. While implementing fear is straightforward, confusion can be a little tricky. `FindGridPath` already internally accounts for the confusion status effect by calling `Pathfinder:MoveRandomly` (although the behavior of that method is also bugged)

- A common bug I see in many mods is that even if they get the entity pathfinding to work, entities will not be able to reach their target should they stay on the bottom corners on the room. Here is a video to illustrate it:

https://github.com/user-attachments/assets/ed12a4a8-4160-4f2e-9248-686471637eac

It's important to bring up that vanilla entities almost always uses `FindGridPath` only to handle their movement, yet the issues described here seemingly does not affect them.

**Comment by namishere** [comment]
I have looked into Pathfinder and its uses before and have admittedly drawn a blank as to why modded attempts at it are so unreliable. Unfortunately, the disassembly for this class is very hard for me to read. 
I've wondered before if somehow the binders themselves are bad... I should look into making new ones for people to test with now that we have an issue for it here.

**Comment by namishere** [comment]
Was looking at `MoveRandomlyAxisAligned`, tested patching it out on an entity that used it and instead calling it in an update callback with a new, freshly made binder. Worked fine. Did not work trying to use base game's binder.

I don't trust any of the `Pathfinder` binders now. I intend to redo all of them.
