### ISSUE TITLE
Hemoptysis Knockback Issue

### ISSUE THREAD

**Issue by BabyblueSheep** [TeamREPENTOGON/REPENTOGON#570]
Hempotysis (and T. Azazel's) sneeze attack applies knockback to the player instead of the enemy. Additionally, impact damage is also applied to the player, potentially leading to situations where the player is dealt several hearts of damage.

https://github.com/user-attachments/assets/fb709f4c-36bb-4675-a35d-1afc99302b93

**Comment by namishere** [comment]
Please use this build and confirm whether or not the issue is fixed: https://github.com/TeamREPENTOGON/REPENTOGON/actions/runs/11335280219

**Comment by BabyblueSheep** [comment]
Doesn't happen with the build.
