### ISSUE TITLE
Encyclopedia – An In-Game Wiki doesnt work on repentogon

### ISSUE THREAD

**Issue by SheriffSans** [TeamREPENTOGON/REPENTOGON#578]
"MC_POST_RENDER" from "Dead Sea Scrolls (Repentance Plus)" failed: ...pedia - an in-game wiki/scripts/encyclopedia_dssmenu.lua:5201: bad argument #1 to 'GetActiveItem' (Invalid ActiveSlot 4)
Stack Traceback:
  in method GetActiveItem
  ...pedia - an in-game wiki/scripts/encyclopedia_dssmenu.lua:5201: in function 'UpdatePlayerStatus'
  ...pedia - an in-game wiki/scripts/encyclopedia_dssmenu.lua:6089: in function 'generate'
  ...pedia - an in-game wiki/scripts/encyclopedia_dssmenu.lua:1509: in function 'Run'
  ...nce/mods/[rgon] repentance plus!/scripts/dssmenucore.lua:1883: in function 'checkMenu'
  ...nce/mods/[rgon] repentance plus!/scripts/dssmenucore.lua:2965: in function at line 2961
  
  Checked with and without mods, the problem only in this mod just gives an error and does not work. Is there any way to fix it?

**Comment by im-tem** [comment]
We advise against using that particular mod as its' author has left the community prior to REPENTOGON's release and this mod has some other issues with it.

**Comment by jerbmega** [comment]
Yes, this won't be fixed because in this case the mod is exhibiting invalid and undefined behavior. Your only option is to report the error to the mod developer.
