### ISSUE TITLE
Question - ZHL License

### ISSUE THREAD

**Issue by Nasa62** [TeamREPENTOGON/REPENTOGON#598]
Hey, did Kilburn say it was MIT licensed to you guys?
When we got our copy from Kilburn_ and finally got an okay out of them to open source things we were told we needed attribution (which doesn't fit MIT).

Just curious where this came from because that can vastly change our licensing restrictions on FTL Hyperspace's ZHL.

**Comment by jerbmega** [comment]
Yeah, we're MIT at his request. If you talk to him again it's possible he'll give the okay relicense your derivative as well. 
![Screenshot_20241203-165020](https://github.com/user-attachments/assets/ba062a8a-b9eb-4479-b8c0-16c0c08e94c3)

**Comment by Nasa62** [comment]
Excellent, well that covers it, I'll talk to our team about if we want to tweak our overall license (from the slightly ridiculous CC-BY-SA) now that that fits for MIT.
