### ISSUE TITLE
Why Repentogon's Debug menu doesnt work?

### ISSUE THREAD

**Issue by Fotny0** [TeamREPENTOGON/REPENTOGON#603]
Im dowloanded Repentogon for optimization but the repentogon's debug menu doesn't work and i can only use the tboi's classic debug and other things (like stats,achievment and more mod,menu) how can i fix it are u guys know anything?

**Comment by epfly6** [comment]
Are you running mod on Repentance or Repentance+?

**Comment by Fotny0** [comment]
> Are you running mod on Repentance or Repentance+?

Repentance (and cracked version :d)

**Comment by jsgnextortex** [comment]
Go to your game folder, where the exe is, look up for dsound.log and copypaste it here.

**Comment by Fotny0** [comment]
and 1 more thing my mods work with no problem but my debug menu always classic debug menu

**Comment by epfly6** [comment]
As stated on site and readme page of repository, Repentogon at the current moment works only on v1.7.9b.J835

**Comment by Fotny0** [comment]
oh okay
